set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN A16 [get_ports clk]
set_property PACKAGE_PIN C15 [get_ports ce]
set_property IOSTANDARD LVCMOS33 [get_ports ce]
set_property PACKAGE_PIN A15 [get_ports rst]

set_property PACKAGE_PIN P1 [get_ports {out[3]}]
set_property PACKAGE_PIN N2 [get_ports {out[2]}]
set_property PACKAGE_PIN N1 [get_ports {out[1]}]
set_property PACKAGE_PIN M2 [get_ports {out[0]}]

create_clock -period 1000000000.000 -name clk -waveform {0.000 500000000.000} [get_ports clk]
